export const AuditAction = {
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  LIST_CREATED: 'LIST_CREATED',
  LIST_ITEM_ADDED: 'LIST_ITEM_ADDED',
  LIST_ITEM_UPDATED: 'LIST_ITEM_UPDATED',
  LIST_ITEM_MOVED: 'LIST_ITEM_MOVED',
  LIST_ITEM_ROLLBACK: 'LIST_ITEM_ROLLBACK',
  LIST_ITEM_PRICING_UPDATED: 'LIST_ITEM_PRICING_UPDATED',
  VERIFICATION_COMPLETED: 'VERIFICATION_COMPLETED',
  PRICING_SETTINGS_UPDATED: 'PRICING_SETTINGS_UPDATED',
  CATEGORY_CREATED: 'CATEGORY_CREATED',
  CATEGORY_UPDATED: 'CATEGORY_UPDATED',
  USER_PASSWORD_CHANGED: 'USER_PASSWORD_CHANGED',
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];
